# Site setings
name: 'Aashi Dutt'
description: 'Aspiring AI Developer'
meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.png'
  greetings: "Hi there! My name is Aashi. I'm an aspiring AI developer based in India, with a background in Electronics and Communications Engineering. Welcome to my Blog :)"
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://aashidutt.github.io
disqus: 'https-aashidutt-github-io'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: aashi.dutt3@email.com
#contact_page_description: "Coming Soon."
thankyou_page_description: "Your message has been successfully sent. I will contact you very soon!"

# Social links
twitter: 'aashidutt'
#facebook: 'username'
github: 'AashiDutt'
#codepen: 'username'
#dribbble: 'username'
medium: '@aashi.dutt3'
#instagram: 'username'
#pinterest: 'username'
linkedin: 'aashi-d-b5554a107'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Projects
    url: /projects
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
